name: Eldorado Bot

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      ELDORADO_EMAIL: ${{ secrets.ELDORADO_EMAIL }}
      ELDORADO_PASSWORD: ${{ secrets.ELDORADO_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node bot.js
